// Auto-generated database types for Supabase
// This file will be generated by: npx supabase gen types typescript --local

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          role: 'customer' | 'admin' | 'super_admin'
          avatar_url: string | null
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone?: string | null
          role?: 'customer' | 'admin' | 'super_admin'
          avatar_url?: string | null
          preferences?: Json
        }
        Update: {
          email?: string
          full_name?: string | null
          phone?: string | null
          role?: 'customer' | 'admin' | 'super_admin'
          avatar_url?: string | null
          preferences?: Json
        }
      }
      exhibitions: {
        Row: {
          id: string
          slug: string
          name: string
          category: 'solar_observatory' | 'science_park' | 'planetarium' | 'astro_gallery' | '3d_theatre' | 'math_lab' | 'physics_lab' | 'holography'
          description: string | null
          short_description: string | null
          duration_minutes: number
          capacity: number
          images: string[]
          video_url: string | null
          virtual_tour_url: string | null
          status: 'active' | 'inactive' | 'coming_soon' | 'maintenance'
          featured: boolean
          display_order: number
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          slug: string
          name: string
          category: 'solar_observatory' | 'science_park' | 'planetarium' | 'astro_gallery' | '3d_theatre' | 'math_lab' | 'physics_lab' | 'holography'
          description?: string | null
          short_description?: string | null
          duration_minutes: number
          capacity: number
          images?: string[]
          video_url?: string | null
          virtual_tour_url?: string | null
          status?: 'active' | 'inactive' | 'coming_soon' | 'maintenance'
          featured?: boolean
          display_order?: number
          metadata?: Json
        }
        Update: {
          slug?: string
          name?: string
          category?: 'solar_observatory' | 'science_park' | 'planetarium' | 'astro_gallery' | '3d_theatre' | 'math_lab' | 'physics_lab' | 'holography'
          description?: string | null
          short_description?: string | null
          duration_minutes?: number
          capacity?: number
          images?: string[]
          video_url?: string | null
          virtual_tour_url?: string | null
          status?: 'active' | 'inactive' | 'coming_soon' | 'maintenance'
          featured?: boolean
          display_order?: number
          metadata?: Json
        }
      }
      bookings: {
        Row: {
          id: string
          booking_reference: string
          user_id: string | null
          guest_email: string | null
          guest_phone: string | null
          guest_name: string | null
          exhibition_id: string | null
          show_id: string | null
          booking_date: string
          time_slot_id: string
          status: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          payment_status: 'pending' | 'paid' | 'refunded' | 'failed'
          total_amount: number
          special_requirements: string | null
          payment_details: Json
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          booking_reference?: string
          user_id?: string | null
          guest_email?: string | null
          guest_phone?: string | null
          guest_name?: string | null
          exhibition_id?: string | null
          show_id?: string | null
          booking_date: string
          time_slot_id: string
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          payment_status?: 'pending' | 'paid' | 'refunded' | 'failed'
          total_amount: number
          special_requirements?: string | null
          payment_details?: Json
          metadata?: Json
        }
        Update: {
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed'
          payment_status?: 'pending' | 'paid' | 'refunded' | 'failed'
          total_amount?: number
          special_requirements?: string | null
          payment_details?: Json
          metadata?: Json
        }
      }
      events: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          event_date: string
          start_time: string
          end_time: string
          location: string
          max_participants: number | null
          registration_required: boolean
          featured_image: string | null
          status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
          booking_enabled: boolean
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          title: string
          slug?: string
          description?: string | null
          event_date: string
          start_time: string
          end_time: string
          location: string
          max_participants?: number | null
          registration_required?: boolean
          featured_image?: string | null
          status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
          booking_enabled?: boolean
          metadata?: Json
        }
        Update: {
          title?: string
          slug?: string
          description?: string | null
          event_date?: string
          start_time?: string
          end_time?: string
          location?: string
          max_participants?: number | null
          registration_required?: boolean
          featured_image?: string | null
          status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
          booking_enabled?: boolean
          metadata?: Json
        }
      }
      event_registrations: {
        Row: {
          id: string
          event_id: string
          user_id: string | null
          name: string
          email: string
          phone: string | null
          status: 'registered' | 'attended' | 'cancelled'
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          event_id: string
          user_id?: string | null
          name: string
          email: string
          phone?: string | null
          status?: 'registered' | 'attended' | 'cancelled'
          metadata?: Json
        }
        Update: {
          status?: 'registered' | 'attended' | 'cancelled'
          metadata?: Json
        }
      }
      // Add other tables as needed...
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_booking_reference: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: {
      user_role: 'customer' | 'admin' | 'super_admin'
      exhibition_category: 'solar_observatory' | 'science_park' | 'planetarium' | 'astro_gallery' | '3d_theatre' | 'math_lab' | 'physics_lab' | 'holography'
      exhibition_status: 'active' | 'inactive' | 'coming_soon' | 'maintenance'
      show_type: 'planetarium' | '3d_theatre' | 'holography'
      ticket_type: 'adult' | 'child' | 'student' | 'senior' | 'group'
      booking_status: 'pending' | 'confirmed' | 'cancelled' | 'completed'
      payment_status: 'pending' | 'paid' | 'refunded' | 'failed'
      event_status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled'
    }
  }
}





